name: pub_dev
publish_to: none
description: The pub.dev website recreated in Flutter.
version: 1.1.0

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  responsive_framework:
    path: responsive_framework
  google_fonts: ^2.3.1
  animations: ^2.0.2
  url_launcher: ^6.0.20
  firebase_core: ^2.3.0
  flick_video_player: ^0.5.0
  video_player: ^2.4.8
  firebase_auth: ^4.1.4
  easy_sidemenu: ^0.4.1
  visibility_detector: ^0.3.3
  brasil_fields: ^1.6.0
  animated_text_kit: ^4.2.2
  intl: ^0.17.0
  side_navigation: ^1.0.4
  sidebarx: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/dart_logo_full.png"
  image_path_ios: "assets/dart_logo_full.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/dart_logo_adaptive.png"

flutter:
  uses-material-design: true

  generate: true
  
  assets:
    - assets/images/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/product_sans_italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_italic.ttf
          style: italic