// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbRdpi4uFMADzC32Lb4hL-1CxNAogVuZQ',
    appId: '1:744060958744:web:750b5bc8e094e43e0feb6d',
    messagingSenderId: '744060958744',
    projectId: 'kienim-88c11',
    authDomain: 'kienim-88c11.firebaseapp.com',
    storageBucket: 'kienim-88c11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArOz0cgRhyzlXKnBCpTd1MnJSof_VMGT4',
    appId: '1:744060958744:android:dea77993e3b396840feb6d',
    messagingSenderId: '744060958744',
    projectId: 'kienim-88c11',
    storageBucket: 'kienim-88c11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJlyBnL-NGtQeh0NtLBz9yPGyK5FTmPxI',
    appId: '1:744060958744:ios:4bf5e35df58f71920feb6d',
    messagingSenderId: '744060958744',
    projectId: 'kienim-88c11',
    storageBucket: 'kienim-88c11.appspot.com',
    iosClientId: '744060958744-6pn137op93eqec38tof8g2tmch81jhc0.apps.googleusercontent.com',
    iosBundleId: 'com.pubdev.pubDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJlyBnL-NGtQeh0NtLBz9yPGyK5FTmPxI',
    appId: '1:744060958744:ios:4bf5e35df58f71920feb6d',
    messagingSenderId: '744060958744',
    projectId: 'kienim-88c11',
    storageBucket: 'kienim-88c11.appspot.com',
    iosClientId: '744060958744-6pn137op93eqec38tof8g2tmch81jhc0.apps.googleusercontent.com',
    iosBundleId: 'com.pubdev.pubDev',
  );
}
